### PR TITLE
Fix pointer arithmetic in MSVC

### LINKED ISSUE #2: MSVC and pointer arithmetic
Hey Peter. Thank you for this implementation! So far I encountered only one problem, not a big deal actually, but MSVC is not happy with pointer arithmetic and throws some errors during compilation:

> vector.c(375): error C2036: void *
vector.c(380): error C2036: void *
vector.c(415): error C2036: void *
vector.c(435): error C2036: void *
vector.c(439): error C2036: void *const
vector.c(473): error C2036: void *
vector.c(488): error C2036: void *

I fixed this with an explicit cast and just want to let you know that such a problem occurs.

### PR DESCRIPTION
**Pull request by nxrighthere**
Fixes #2

### CODE REVIEW

**Comment by nxrighthere** [comment]
I just realized that this change is valid only if the data size equals the size of an explicit cast (my case), so it will not work properly for other cases...

**Comment by nxrighthere** [comment]
I need to think about this change more carefully. 🤔

**Comment by nxrighthere** [comment]
I just found that GCC is utilizing the [extension](https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Pointer-Arith.html) for this. I wonder, will the current approach with simple explicit cast void pointer to char pointer work correctly in MSVC as it works in GCC. 🤔

**Comment by goldsborough** [comment]
Wouldn't casting to `char*`/`uint8_t*` work?

**Comment by nxrighthere** [comment]
Well, it seems that `char*` works fine. Can't reopen this pull request, unfortunately.

**Comment by nxrighthere** [comment]
Please, feel free to merge this, my fork is gone, but luckily the actual changes are very small.

**Pull request closed without merging**
